/*
TrueNAS RESTful API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package truenas

import (
	"encoding/json"
)

// ReplacementBrick struct for ReplacementBrick
type ReplacementBrick struct {
	PeerName *string `json:"peer_name,omitempty"`
	PeerPath *string `json:"peer_path,omitempty"`
}

// NewReplacementBrick instantiates a new ReplacementBrick object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReplacementBrick() *ReplacementBrick {
	this := ReplacementBrick{}
	return &this
}

// NewReplacementBrickWithDefaults instantiates a new ReplacementBrick object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReplacementBrickWithDefaults() *ReplacementBrick {
	this := ReplacementBrick{}
	return &this
}

// GetPeerName returns the PeerName field value if set, zero value otherwise.
func (o *ReplacementBrick) GetPeerName() string {
	if o == nil || o.PeerName == nil {
		var ret string
		return ret
	}
	return *o.PeerName
}

// GetPeerNameOk returns a tuple with the PeerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReplacementBrick) GetPeerNameOk() (*string, bool) {
	if o == nil || o.PeerName == nil {
		return nil, false
	}
	return o.PeerName, true
}

// HasPeerName returns a boolean if a field has been set.
func (o *ReplacementBrick) HasPeerName() bool {
	if o != nil && o.PeerName != nil {
		return true
	}

	return false
}

// SetPeerName gets a reference to the given string and assigns it to the PeerName field.
func (o *ReplacementBrick) SetPeerName(v string) {
	o.PeerName = &v
}

// GetPeerPath returns the PeerPath field value if set, zero value otherwise.
func (o *ReplacementBrick) GetPeerPath() string {
	if o == nil || o.PeerPath == nil {
		var ret string
		return ret
	}
	return *o.PeerPath
}

// GetPeerPathOk returns a tuple with the PeerPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReplacementBrick) GetPeerPathOk() (*string, bool) {
	if o == nil || o.PeerPath == nil {
		return nil, false
	}
	return o.PeerPath, true
}

// HasPeerPath returns a boolean if a field has been set.
func (o *ReplacementBrick) HasPeerPath() bool {
	if o != nil && o.PeerPath != nil {
		return true
	}

	return false
}

// SetPeerPath gets a reference to the given string and assigns it to the PeerPath field.
func (o *ReplacementBrick) SetPeerPath(v string) {
	o.PeerPath = &v
}

func (o ReplacementBrick) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.PeerName != nil {
		toSerialize["peer_name"] = o.PeerName
	}
	if o.PeerPath != nil {
		toSerialize["peer_path"] = o.PeerPath
	}
	return json.Marshal(toSerialize)
}

type NullableReplacementBrick struct {
	value *ReplacementBrick
	isSet bool
}

func (v NullableReplacementBrick) Get() *ReplacementBrick {
	return v.value
}

func (v *NullableReplacementBrick) Set(val *ReplacementBrick) {
	v.value = val
	v.isSet = true
}

func (v NullableReplacementBrick) IsSet() bool {
	return v.isSet
}

func (v *NullableReplacementBrick) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReplacementBrick(val *ReplacementBrick) *NullableReplacementBrick {
	return &NullableReplacementBrick{value: val, isSet: true}
}

func (v NullableReplacementBrick) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReplacementBrick) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
