/*
TrueNAS RESTful API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package truenas

import (
	"encoding/json"
)

// Cachevdevs struct for Cachevdevs
type Cachevdevs struct {
	Type  *string  `json:"type,omitempty"`
	Disks []string `json:"disks,omitempty"`
}

// NewCachevdevs instantiates a new Cachevdevs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCachevdevs() *Cachevdevs {
	this := Cachevdevs{}
	return &this
}

// NewCachevdevsWithDefaults instantiates a new Cachevdevs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCachevdevsWithDefaults() *Cachevdevs {
	this := Cachevdevs{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Cachevdevs) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cachevdevs) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Cachevdevs) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Cachevdevs) SetType(v string) {
	o.Type = &v
}

// GetDisks returns the Disks field value if set, zero value otherwise.
func (o *Cachevdevs) GetDisks() []string {
	if o == nil || o.Disks == nil {
		var ret []string
		return ret
	}
	return o.Disks
}

// GetDisksOk returns a tuple with the Disks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cachevdevs) GetDisksOk() ([]string, bool) {
	if o == nil || o.Disks == nil {
		return nil, false
	}
	return o.Disks, true
}

// HasDisks returns a boolean if a field has been set.
func (o *Cachevdevs) HasDisks() bool {
	if o != nil && o.Disks != nil {
		return true
	}

	return false
}

// SetDisks gets a reference to the given []string and assigns it to the Disks field.
func (o *Cachevdevs) SetDisks(v []string) {
	o.Disks = v
}

func (o Cachevdevs) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Disks != nil {
		toSerialize["disks"] = o.Disks
	}
	return json.Marshal(toSerialize)
}

type NullableCachevdevs struct {
	value *Cachevdevs
	isSet bool
}

func (v NullableCachevdevs) Get() *Cachevdevs {
	return v.value
}

func (v *NullableCachevdevs) Set(val *Cachevdevs) {
	v.value = val
	v.isSet = true
}

func (v NullableCachevdevs) IsSet() bool {
	return v.isSet
}

func (v *NullableCachevdevs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCachevdevs(val *Cachevdevs) *NullableCachevdevs {
	return &NullableCachevdevs{value: val, isSet: true}
}

func (v NullableCachevdevs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCachevdevs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
