/*
TrueNAS RESTful API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package truenas

import (
	"encoding/json"
	"fmt"
)

// Copies struct for Copies
type Copies struct {
	Int32  *int32
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Copies) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into int32
	err = json.Unmarshal(data, &dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			return nil // data stored in dst.Int32, return on the first match
		}
	} else {
		dst.Int32 = nil
	}

	// try to unmarshal JSON data into string
	err = json.Unmarshal(data, &dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("Data failed to match schemas in anyOf(Copies)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *Copies) MarshalJSON() ([]byte, error) {
	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableCopies struct {
	value *Copies
	isSet bool
}

func (v NullableCopies) Get() *Copies {
	return v.value
}

func (v *NullableCopies) Set(val *Copies) {
	v.value = val
	v.isSet = true
}

func (v NullableCopies) IsSet() bool {
	return v.isSet
}

func (v *NullableCopies) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCopies(val *Copies) *NullableCopies {
	return &NullableCopies{value: val, isSet: true}
}

func (v NullableCopies) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCopies) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
