/*
TrueNAS RESTful API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package truenas

import (
	"encoding/json"
)

// ChartReleaseRollback struct for ChartReleaseRollback
type ChartReleaseRollback struct {
	ReleaseName          *string                `json:"release_name,omitempty"`
	RollbackOptions      *ChartReleaseRollback1 `json:"rollback_options,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ChartReleaseRollback ChartReleaseRollback

// NewChartReleaseRollback instantiates a new ChartReleaseRollback object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChartReleaseRollback() *ChartReleaseRollback {
	this := ChartReleaseRollback{}
	return &this
}

// NewChartReleaseRollbackWithDefaults instantiates a new ChartReleaseRollback object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChartReleaseRollbackWithDefaults() *ChartReleaseRollback {
	this := ChartReleaseRollback{}
	return &this
}

// GetReleaseName returns the ReleaseName field value if set, zero value otherwise.
func (o *ChartReleaseRollback) GetReleaseName() string {
	if o == nil || o.ReleaseName == nil {
		var ret string
		return ret
	}
	return *o.ReleaseName
}

// GetReleaseNameOk returns a tuple with the ReleaseName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartReleaseRollback) GetReleaseNameOk() (*string, bool) {
	if o == nil || o.ReleaseName == nil {
		return nil, false
	}
	return o.ReleaseName, true
}

// HasReleaseName returns a boolean if a field has been set.
func (o *ChartReleaseRollback) HasReleaseName() bool {
	if o != nil && o.ReleaseName != nil {
		return true
	}

	return false
}

// SetReleaseName gets a reference to the given string and assigns it to the ReleaseName field.
func (o *ChartReleaseRollback) SetReleaseName(v string) {
	o.ReleaseName = &v
}

// GetRollbackOptions returns the RollbackOptions field value if set, zero value otherwise.
func (o *ChartReleaseRollback) GetRollbackOptions() ChartReleaseRollback1 {
	if o == nil || o.RollbackOptions == nil {
		var ret ChartReleaseRollback1
		return ret
	}
	return *o.RollbackOptions
}

// GetRollbackOptionsOk returns a tuple with the RollbackOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChartReleaseRollback) GetRollbackOptionsOk() (*ChartReleaseRollback1, bool) {
	if o == nil || o.RollbackOptions == nil {
		return nil, false
	}
	return o.RollbackOptions, true
}

// HasRollbackOptions returns a boolean if a field has been set.
func (o *ChartReleaseRollback) HasRollbackOptions() bool {
	if o != nil && o.RollbackOptions != nil {
		return true
	}

	return false
}

// SetRollbackOptions gets a reference to the given ChartReleaseRollback1 and assigns it to the RollbackOptions field.
func (o *ChartReleaseRollback) SetRollbackOptions(v ChartReleaseRollback1) {
	o.RollbackOptions = &v
}

func (o ChartReleaseRollback) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ReleaseName != nil {
		toSerialize["release_name"] = o.ReleaseName
	}
	if o.RollbackOptions != nil {
		toSerialize["rollback_options"] = o.RollbackOptions
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *ChartReleaseRollback) UnmarshalJSON(bytes []byte) (err error) {
	varChartReleaseRollback := _ChartReleaseRollback{}

	if err = json.Unmarshal(bytes, &varChartReleaseRollback); err == nil {
		*o = ChartReleaseRollback(varChartReleaseRollback)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "release_name")
		delete(additionalProperties, "rollback_options")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableChartReleaseRollback struct {
	value *ChartReleaseRollback
	isSet bool
}

func (v NullableChartReleaseRollback) Get() *ChartReleaseRollback {
	return v.value
}

func (v *NullableChartReleaseRollback) Set(val *ChartReleaseRollback) {
	v.value = val
	v.isSet = true
}

func (v NullableChartReleaseRollback) IsSet() bool {
	return v.isSet
}

func (v *NullableChartReleaseRollback) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChartReleaseRollback(val *ChartReleaseRollback) *NullableChartReleaseRollback {
	return &NullableChartReleaseRollback{value: val, isSet: true}
}

func (v NullableChartReleaseRollback) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChartReleaseRollback) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
